### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Zilster-Luik** [kgzylwip/ggdm#1]
I followed the instructions provided, and upon launching the game at character select I got two separate errors: 
1) Info: Failed to copy the meter to the temporary path
2) Info: Failed to load the meter.

All 6 files I extracted are in my bin64, I am launching Gw2-64 from within my Guild Wars 2 folder, and I installed both the DirectX and Visual C++ files that were linked. Thanks in advance for any help with the issue!

**Comment by kgzylwip** [comment]
This is likely an issue with write permissions on your game directory. The loader supports hot reloading the meter, and in order to do so, it attempts to copy meter.dll as tmp.dll into the bin64 directory, then attempts to load tmp.dll.

Try moving the game directory to some place with write permissions, ie. "C:\Guild Wars 2". This is what I would recommend since permissions are useful for some of the meter features, like personal DPS recording.

If this doesn't fix the problem, then I'd probably need more information - what version of Windows you're running in particular would help.

**Comment by kgzylwip** [comment]
I suppose I'll close this issue because the loader/meter now has a fallback case for this situation . If turns out to be a different issue, feel free to open another one though.

**Comment by Zilster-Luik** [comment]
Thanks! That fixed the issue. That was the speediest response and resolution I've ever seen.
